name: VUIET_RELEASE_CI
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Publish
        run: pnpm run ci:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          prerelease: false
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: ${{github.ref_name}}
          title: 'Release ${{github.ref_name}}'
